# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointPercentiles
                                 A QGIS plugin
 This plugin calculates and styles percentile classifications for a point dataset.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-28
        copyright            : (C) 2019 by Jeff Hamilton
        email                : jeffh@bmcminerals.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PointPercentiles class from file PointPercentiles.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .point_percentiles import PointPercentiles
    return PointPercentiles(iface)
